runtime: nodejs18
env: standard
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  # Serve assets directory
  - url: /assets/(.*)
    static_files: dist/assets/\1
    upload: dist/assets/.*
    secure: always

  # Serve static files
  - url: /(.*\.(ico|png|jpg|jpeg|svg|gif))$
    static_files: dist/\1
    upload: dist/.*\.(ico|png|jpg|jpeg|svg|gif)$
    secure: always

  # Serve index.html for all other routes (SPA support)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

env_variables:
  NODE_ENV: "production" 